name: Manual packaging test

on:
  # Manual trigger
  workflow_dispatch:

jobs:
  
  release:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      # Needed for locale files
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      # "GITHUB_TOKEN" is a secret always provided to the workflow
      # for your own token, the name cannot start with "GITHUB_"
    
    steps:

      - name: Clone project
        uses: actions/checkout@v4
      
      - name: Package w/o release
        uses: BigWigsMods/packager@v2
        with:
        # Skip upload
          args: -d -g retail
