name: Package and release

on:
  push:
    tags:
      # Start actions with version 'v1.0.0'; allow up to 'v1.99.999+'
      - 'v1.[0-9][0-9].[0-9]+'

jobs:
  
  release:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      # "GITHUB_TOKEN" is a secret always provided to the workflow
      # for your own token, the name cannot start with "GITHUB_"
    
    steps:

      - name: Clone project
        uses: actions/checkout@v4
      
      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -g retail
